import mongoose from 'mongoose';

const QuerySchema = new mongoose.Schema({
  queryId: {
    type: String,
    unique: true,
    sparse: true,
    default: null
  },
  name: {
    type: String,
    required: [true, 'Full name is required'],
    trim: true
  },
  mobile: {
    type: String,
    required: [true, 'Mobile number is required'],
    match: [/^[6-9]\d{9}$/, 'Please provide a valid 10-digit mobile number']
  },
  ward: {
    type: Number,
    required: [true, 'Ward number is required'],
    min: [1, 'Ward number must be at least 1'],
    max: [20, 'Ward number cannot exceed 20']
  },
  category: {
    type: String,
    enum: [
      'Water',
      'Road',
      'Electricity',
      'Health/PHC',
      'Pension',
      'Ration',
      'Certificates',
      'Drainage',
      'Street Light',
      'Anganwadi',
      'School',
      'Others'
    ],
    required: [true, 'Category is required']
  },
  subject: {
    type: String,
    required: [true, 'Subject is required'],
    maxlength: [100, 'Subject cannot exceed 100 characters'],
    trim: true
  },
  description: {
    type: String,
    required: [true, 'Description is required'],
    trim: true
  },
  address: {
    type: String,
    default: ''
  },
  photo: {
    type: String,
    default: null
  },
  status: {
    type: String,
    enum: ['New', 'In Progress', 'Resolved', 'Rejected'],
    default: 'New'
  },
  priority: {
    type: String,
    enum: ['High', 'Medium', 'Low'],
    default: 'Medium'
  },
  assignedTo: {
    type: String,
    enum: ['Ward Member-1', 'Ward Member-2', 'Ward Member-3', 'Ward Member-4', 'Ward Member-5', 'Ward Member-6', 'Ward Member-7', 'Ward Member-8', 'Ward Member-9', 'Ward Member-10', 'Secretary', 'JE', 'Pradhan'],
    default: null
  },
  adminRemarks: {
    type: String,
    default: ''
  },
  internalNotes: {
    type: String,
    default: ''
  },
  resolutionPhoto: {
    type: String,
    default: null
  },
  escalate: {
    type: Boolean,
    default: false
  },
  acknowledgedAt: {
    type: Date,
    default: null
  },
  resolvedAt: {
    type: Date,
    default: null
  },
  auditLog: [
    {
      action: String,
      changedBy: String,
      changedAt: {
        type: Date,
        default: Date.now
      },
      from: mongoose.Schema.Types.Mixed,
      to: mongoose.Schema.Types.Mixed
    }
  ]
}, {
  timestamps: true
});

// Pre-save hook to update escalate flag based on SLA
QuerySchema.pre('save', function(next) {
  if (!this.queryId && this.isNew) {
    // queryId will be generated by API before save
  }
  next();
});

const Query = mongoose.models.Query || mongoose.model('Query', QuerySchema);

export default Query;
